package com.shuttletechnologies.speakercleaner.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

data class StringResources(
    val appName: String,
    val tabClean: String,
    val tabGenerator: String,
    val tabDiagnostics: String,
    val tabHistory: String,
    val tabSettings: String,

    val subClean: String,
    val subGenerator: String,
    val subDiagnostics: String,
    val subHistory: String,
    val subSettings: String,

    val badgePro: String,
    val badgeActive: String,
    val badgeReady: String,

    // Clean Screen
    val speakerTargetTitle: String,
    val targetLoudspeaker: String,
    val targetEarpiece: String,
    val modeWaterEject: String,
    val modeDustBlast: String,
    val modeDeepClean: String,
    val modeQuickBlast: String,
    val btnStartCleaning: String,
    val btnStopCleaning: String,
    val statusCleaning: String,
    val statusCompleted: String,
    val statusIdle: String,
    val tipHeader: String,
    val tip1: String,
    val tip2: String,
    val tip3: String,
    val phase1: String,
    val phase2: String,
    val phase3: String,
    val remainingSec: String,

    // Generator Screen
    val generatorTitle: String,
    val waveformTitle: String,
    val waveSine: String,
    val waveSquare: String,
    val waveTriangle: String,
    val waveSawtooth: String,
    val frequencyLabel: String,
    val presetsTitle: String,
    val presetWater: String,
    val presetDust: String,
    val presetConcert: String,
    val presetTest: String,
    val presetUltra: String,
    val btnPlayTone: String,
    val btnStopTone: String,
    val volumeLabel: String,

    // Diagnostics Screen
    val diagStereoTitle: String,
    val diagStereoDesc: String,
    val btnTestLeft: String,
    val btnTestRight: String,
    val btnTestBoth: String,
    val diagSweepTitle: String,
    val diagSweepDesc: String,
    val btnStartSweep: String,
    val btnStopSweep: String,
    val diagNoiseTitle: String,
    val btnWhiteNoise: String,
    val btnPinkNoise: String,
    val diagMeterTitle: String,
    val diagMeterDesc: String,
    val btnStartMeter: String,
    val btnStopMeter: String,
    val liveDb: String,
    val peakDb: String,
    val recordBefore: String,
    val recordAfter: String,
    val micPermissionRequired: String,
    val grantPermission: String,

    // History Screen
    val historyTitle: String,
    val historyEmpty: String,
    val statTotalCleans: String,
    val statWaterCleans: String,
    val statDustCleans: String,
    val statLastClean: String,
    val tipAcousticTitle: String,
    val tipAcousticDesc: String,
    val tipPositionTitle: String,
    val tipPositionDesc: String,
    val never: String,

    // Settings Screen
    val settingsThemeTitle: String,
    val themeSystem: String,
    val themeDarkStudio: String,
    val themeAmoled: String,
    val themeLight: String,
    val settingsLanguageTitle: String,
    val settingsSecurityTitle: String,
    val pinLock: String,
    val biometricUnlock: String,
    val setupPin: String,
    val pinPrompt: String,
    val pinIncorrect: String,
    val settingsAboutTitle: String,
    val rateUsTitle: String,
    val rateUsDesc: String,
    val feedbackTitle: String,
    val feedbackDesc: String,
    val moreAppsTitle: String,
    val privacyPolicyTitle: String,
    val versionText: String,
    val copiedFeedback: String,

    // Dialogs & Security
    val exitTitle: String,
    val exitMessage: String,
    val btnRateUs: String,
    val btnLater: String,
    val btnExit: String,
    val unlockTitle: String,
    val enterPin: String,
    val biometricPromptTitle: String,
    val biometricPromptSubtitle: String,

    val modeUltrasonic: String = "Ultrasonic",
    val subLanguage: String = "Tap to switch language",
    val moreAppsDesc: String = "Explore more utilities by Shuttle Technologies",
    val btnSave: String = "Save PIN",
    val btnCancel: String = "Cancel",
    val confirmPin: String = "Confirm 4-Digit PIN"
)

val EnglishStrings = StringResources(
    appName = "Speaker Cleaner",
    tabClean = "Clean",
    tabGenerator = "Generator",
    tabDiagnostics = "Diagnostics",
    tabHistory = "History",
    tabSettings = "Settings",

    subClean = "Water & Dust Ejector",
    subGenerator = "Frequency Synthesizer",
    subDiagnostics = "Acoustic Health & Meter",
    subHistory = "Session Log & Stats",
    subSettings = "App Preferences",

    badgePro = "PRO",
    badgeActive = "ACTIVE",
    badgeReady = "READY",

    speakerTargetTitle = "Speaker Target",
    targetLoudspeaker = "Loudspeaker",
    targetEarpiece = "Ear Receiver",
    modeWaterEject = "Water Eject",
    modeDustBlast = "Dust Blast",
    modeDeepClean = "Deep Clean",
    modeQuickBlast = "Quick Blast",
    btnStartCleaning = "Start Cleaning",
    btnStopCleaning = "Stop Cleaning",
    statusCleaning = "Cleaning Active...",
    statusCompleted = "Cleaning Complete ✓",
    statusIdle = "Ready to Clean",
    tipHeader = "For Maximum Ejection Efficiency:",
    tip1 = "1. Turn phone volume to 100% MAXIMUM.",
    tip2 = "2. Position phone facing DOWN at a 45° angle.",
    tip3 = "3. Disconnect headphones & Bluetooth devices.",
    phase1 = "Phase 1: Low-Resonance Oscillation",
    phase2 = "Phase 2: Stepped Air Displacement",
    phase3 = "Phase 3: High-Frequency Vaporization",
    remainingSec = "Remaining",

    generatorTitle = "Precision Frequency Generator",
    waveformTitle = "Waveform Type",
    waveSine = "Sine",
    waveSquare = "Square",
    waveTriangle = "Triangle",
    waveSawtooth = "Sawtooth",
    frequencyLabel = "Frequency",
    presetsTitle = "Acoustic Presets",
    presetWater = "165 Hz • Water Resonator",
    presetDust = "320 Hz • Dust Agitator",
    presetConcert = "440 Hz • Concert Pitch",
    presetTest = "1,000 Hz • Clarity Test",
    presetUltra = "14,000 Hz • Ultrasonic",
    btnPlayTone = "Play Tone",
    btnStopTone = "Stop Tone",
    volumeLabel = "Output Volume",

    diagStereoTitle = "Stereo Separation Check",
    diagStereoDesc = "Verify left and right audio channels independently.",
    btnTestLeft = "Left Channel",
    btnTestRight = "Right Channel",
    btnTestBoth = "Stereo Center",
    diagSweepTitle = "Frequency Sweep Test",
    diagSweepDesc = "Sweep 20 Hz to 20,000 Hz to detect speaker distortion or rattle.",
    btnStartSweep = "Start Sweep",
    btnStopSweep = "Stop Sweep",
    diagNoiseTitle = "Acoustic Burn-In Noise",
    btnWhiteNoise = "White Noise",
    btnPinkNoise = "Pink Noise",
    diagMeterTitle = "Sound Decibel (dB) Meter",
    diagMeterDesc = "Measure speaker sound level before and after cleaning to verify volume recovery.",
    btnStartMeter = "Start Decibel Meter",
    btnStopMeter = "Stop Decibel Meter",
    liveDb = "Live dB",
    peakDb = "Peak dB",
    recordBefore = "Save as Before Level",
    recordAfter = "Save as After Level",
    micPermissionRequired = "Microphone permission required for Decibel Meter.",
    grantPermission = "Grant Permission",

    historyTitle = "Cleaning History",
    historyEmpty = "No cleaning sessions recorded yet. Start your first cleaning cycle above!",
    statTotalCleans = "Total Clean Cycles",
    statWaterCleans = "Water Ejections",
    statDustCleans = "Dust Cleans",
    statLastClean = "Last Cleaning",
    tipAcousticTitle = "How Acoustic Ejection Works",
    tipAcousticDesc = "Physical sound waves push air through the speaker chamber at resonant frequencies (140-165 Hz), mechanically dislodging trapped water droplets and clearing clogged speaker mesh.",
    tipPositionTitle = "Why Face Down?",
    tipPositionDesc = "Gravity works together with acoustic air displacement to allow droplets to flow freely out of speaker grilles rather than settling back onto internal coils.",
    never = "Never",

    settingsThemeTitle = "App Theme",
    themeSystem = "System Default",
    themeDarkStudio = "Dark Studio",
    themeAmoled = "Pitch Black AMOLED",
    themeLight = "Crisp Light",
    settingsLanguageTitle = "Language / Idioma",
    settingsSecurityTitle = "App Security & Privacy",
    pinLock = "PIN Passcode Lock",
    biometricUnlock = "Biometric (Fingerprint / Face)",
    setupPin = "Setup 4-Digit PIN",
    pinPrompt = "Enter your 4-digit PIN",
    pinIncorrect = "Incorrect PIN. Try again.",
    settingsAboutTitle = "About & Community",
    rateUsTitle = "Rate Us on Google Play",
    rateUsDesc = "Love Speaker Cleaner? Help us by leaving a 5-star review!",
    feedbackTitle = "Feedback & Support",
    feedbackDesc = "Contact our engineering team for help or suggestions.",
    moreAppsTitle = "More Apps by Shuttle Technologies",
    privacyPolicyTitle = "Privacy Policy",
    versionText = "Version 1.0.0 (Build 1)",
    copiedFeedback = "Support email copied ✓",

    exitTitle = "Enjoying Speaker Cleaner?",
    exitMessage = "Please take a moment to leave a 5-star review on Google Play. Your support helps keep this tool free and ad-light!",
    btnRateUs = "Rate 5 Stars ★",
    btnLater = "Later",
    btnExit = "Exit App",
    unlockTitle = "Security Verification",
    enterPin = "Enter PIN to Unlock",
    biometricPromptTitle = "Unlock Speaker Cleaner",
    biometricPromptSubtitle = "Use biometric authentication to access"
)

val SpanishStrings = EnglishStrings.copy(
    tabClean = "Limpiar",
    tabGenerator = "Generador",
    tabDiagnostics = "Diagnóstico",
    tabHistory = "Historial",
    tabSettings = "Ajustes",
    subClean = "Expulsor de Agua y Polvo",
    subGenerator = "Sintetizador de Frecuencia",
    subDiagnostics = "Salud Acústica y Decibelímetro",
    subHistory = "Registro y Estadísticas",
    subSettings = "Preferencias",
    targetLoudspeaker = "Altavoz Principal",
    targetEarpiece = "Receptor de Llamadas",
    modeWaterEject = "Expulsar Agua",
    modeDustBlast = "Limpiar Polvo",
    modeDeepClean = "Limpieza Profunda",
    modeQuickBlast = "Limpieza Rápida",
    btnStartCleaning = "Iniciar Limpieza",
    btnStopCleaning = "Detener Limpieza",
    statusCleaning = "Limpieza Activa...",
    statusCompleted = "Limpieza Completada ✓",
    statusIdle = "Listo para Limpiar",
    tipHeader = "Para Máxima Eficiencia:",
    tip1 = "1. Sube el volumen del teléfono al 100% MÁXIMO.",
    tip2 = "2. Coloca el teléfono boca abajo a 45°.",
    tip3 = "3. Desconecta auriculares y Bluetooth.",
    phase1 = "Fase 1: Oscilación de Baja Resonancia",
    phase2 = "Phase 2: Desplazamiento de Aire",
    phase3 = "Fase 3: Vaporización de Alta Frecuencia",
    remainingSec = "Restante",
    generatorTitle = "Generador de Frecuencia",
    waveformTitle = "Tipo de Onda",
    btnPlayTone = "Reproducir Tono",
    btnStopTone = "Detener Tono",
    diagStereoTitle = "Prueba de Separación Estéreo",
    btnTestLeft = "Canal Izquierdo",
    btnTestRight = "Canal Derecho",
    btnTestBoth = "Centro Estéreo",
    diagMeterTitle = "Decibelímetro (dB)",
    btnStartMeter = "Iniciar Medidor",
    btnStopMeter = "Detener Medidor",
    historyTitle = "Historial de Limpieza",
    historyEmpty = "Aún no hay sesiones registradas.",
    statTotalCleans = "Limpiezas Totales",
    settingsThemeTitle = "Tema de la Aplicación",
    rateUsTitle = "Califícanos en Google Play",
    feedbackTitle = "Soporte y Comentarios",
    btnRateUs = "Calificar 5 Estrellas ★",
    btnLater = "Más tarde",
    btnExit = "Salir"
)

val GermanStrings = EnglishStrings.copy(
    tabClean = "Reinigen",
    tabGenerator = "Generator",
    tabDiagnostics = "Diagnose",
    tabHistory = "Verlauf",
    tabSettings = "Einstellungen",
    subClean = "Wasser- & Staubausstoßer",
    subGenerator = "Frequenzsynthesizer",
    subDiagnostics = "Lautsprechergesundheit & dB",
    subHistory = "Sitzungsprotokoll",
    subSettings = "App-Einstellungen",
    targetLoudspeaker = "Hauptlautsprecher",
    targetEarpiece = "Hörmuschel",
    modeWaterEject = "Wasser ausstoßen",
    modeDustBlast = "Staub entfernen",
    modeDeepClean = "Tiefenreinigung",
    modeQuickBlast = "Schnellreinigung",
    btnStartCleaning = "Reinigung starten",
    btnStopCleaning = "Reinigung stoppen",
    statusCleaning = "Reinigung aktiv...",
    statusCompleted = "Reinigung abgeschlossen ✓",
    tip1 = "1. Lautstärke auf 100% MAXIMUM einstellen.",
    tip2 = "2. Telefon mit Bildschirm nach unten bei 45° halten.",
    tip3 = "3. Kopfhörer trennen.",
    btnPlayTone = "Ton abspielen",
    btnStopTone = "Ton stoppen",
    rateUsTitle = "Auf Google Play bewerten",
    btnRateUs = "5 Sterne bewerten ★",
    btnLater = "Später",
    btnExit = "Beenden"
)

val FrenchStrings = EnglishStrings.copy(
    tabClean = "Nettoyer",
    tabGenerator = "Générateur",
    tabDiagnostics = "Diagnostic",
    tabHistory = "Historique",
    tabSettings = "Paramètres",
    subClean = "Éjecteur d'eau et de poussière",
    subGenerator = "Synthétiseur de fréquence",
    subDiagnostics = "Santé audio & décibels",
    targetLoudspeaker = "Haut-parleur principal",
    targetEarpiece = "Écouteur d'appel",
    modeWaterEject = "Éjecter l'eau",
    modeDustBlast = "Éliminer poussière",
    modeDeepClean = "Nettoyage en profondeur",
    modeQuickBlast = "Nettoyage rapide",
    btnStartCleaning = "Démarrer le nettoyage",
    btnStopCleaning = "Arrêter le nettoyage",
    statusCleaning = "Nettoyage en cours...",
    statusCompleted = "Nettoyage terminé ✓",
    tip1 = "1. Montez le volume à 100% MAXIMUM.",
    tip2 = "2. Placez l'écran face vers le bas à 45°.",
    tip3 = "3. Débranchez les écouteurs.",
    btnRateUs = "Noter 5 étoiles ★",
    btnLater = "Plus tard",
    btnExit = "Quitter"
)

val JapaneseStrings = EnglishStrings.copy(
    tabClean = "クリーニング",
    tabGenerator = "周波数生成",
    tabDiagnostics = "診断テスト",
    tabHistory = "履歴",
    tabSettings = "設定",
    subClean = "水抜き＆ホコリ除去",
    subGenerator = "高精度周波数ジェネレーター",
    subDiagnostics = "音響ヘルス＆デシベル測定",
    targetLoudspeaker = "メインスピーカー",
    targetEarpiece = "通話レシーバー",
    modeWaterEject = "水抜きモード",
    modeDustBlast = "ホコリ除去モード",
    modeDeepClean = "ディープクリーン",
    modeQuickBlast = "クイック噴射",
    btnStartCleaning = "クリーニング開始",
    btnStopCleaning = "停止する",
    statusCleaning = "噴射中...",
    statusCompleted = "完了しました ✓",
    tip1 = "1. 音量を100%最大に設定してください。",
    tip2 = "2. 画面を下に向けて45度に傾けてください。",
    tip3 = "3. イヤホンを外してください。",
    btnRateUs = "5つ星で評価 ★",
    btnLater = "後で",
    btnExit = "終了"
)

val ArabicStrings = EnglishStrings.copy(
    tabClean = "تنظيف",
    tabGenerator = "المولد",
    tabDiagnostics = "التشخيص",
    tabHistory = "السجل",
    tabSettings = "الإعدادات",
    subClean = "طارد الماء والغبار",
    subGenerator = "توليد الترددات الصوتية",
    subDiagnostics = "صحة السماعة ومقياس الصوت",
    targetLoudspeaker = "مكبر الصوت الرئيسي",
    targetEarpiece = "سماعة المكالمات",
    modeWaterEject = "طرد الماء",
    modeDustBlast = "تنظيف الغبار",
    modeDeepClean = "تنظيف عميق",
    modeQuickBlast = "تنظيف سريع",
    btnStartCleaning = "بدء التنظيف",
    btnStopCleaning = "إيقاف التنظيف",
    statusCleaning = "جاري التنظيف الآن...",
    statusCompleted = "اكتمل التنظيف ✓",
    tip1 = "١. ارفع صوت الهاتف إلى ١٠٠٪ كحد أقصى.",
    tip2 = "٢. ضع الهاتف مقلوباً بزاوية ٤٥ درجة.",
    tip3 = "٣. افصل سماعات الرأس والبلوتوث.",
    btnRateUs = "تقييم 5 نجوم ★",
    btnLater = "لاحقاً",
    btnExit = "خروج"
)

val HindiStrings = EnglishStrings.copy(
    tabClean = "सफाई",
    tabGenerator = "जेनरेटर",
    tabDiagnostics = "जांच",
    tabHistory = "इतिहास",
    tabSettings = "सेटिंग्स",
    subClean = "पानी और धूल निकालने वाला",
    subGenerator = "सटीक फ्रीक्वेंसी जनरेटर",
    subDiagnostics = "स्पीकर स्वास्थ्य एवं डेसिबल मीटर",
    targetLoudspeaker = "मुख्य लाउडस्पीकर",
    targetEarpiece = "कॉल रिसीवर स्पीकर",
    modeWaterEject = "पानी निकालें",
    modeDustBlast = "धूल साफ करें",
    modeDeepClean = "डीप क्लीन",
    modeQuickBlast = "त्वरित सफाई",
    btnStartCleaning = "सफाई शुरू करें",
    btnStopCleaning = "सफाई रोकें",
    statusCleaning = "सफाई जारी है...",
    statusCompleted = "सफाई पूर्ण हुई ✓",
    tip1 = "1. फोन का वॉल्यूम 100% अधिकतम करें।",
    tip2 = "2. फोन को उल्टा (स्क्रीन नीचे) 45° झुका कर रखें।",
    tip3 = "3. हेडफोन और ब्लूटूथ हटा दें।",
    btnRateUs = "5 स्टार रेटिंग दें ★",
    btnLater = "बाद में",
    btnExit = "बाहर निकलें"
)

val PortugueseStrings = EnglishStrings.copy(
    tabClean = "Limpar",
    tabGenerator = "Gerador",
    tabDiagnostics = "Diagnóstico",
    tabHistory = "Histórico",
    tabSettings = "Ajustes",
    subClean = "Ejetor de Água e Poeira",
    subGenerator = "Sintetizador de Frequência",
    subDiagnostics = "Saúde do Alto-falante & dB",
    targetLoudspeaker = "Alto-falante Principal",
    targetEarpiece = "Receptor de Chamadas",
    modeWaterEject = "Ejetar Água",
    modeDustBlast = "Limpar Poeira",
    modeDeepClean = "Limpeza Profunda",
    modeQuickBlast = "Limpeza Rápida",
    btnStartCleaning = "Iniciar Limpeza",
    btnStopCleaning = "Parar Limpeza",
    statusCleaning = "Limpeza em Andamento...",
    statusCompleted = "Limpeza Concluída ✓",
    btnRateUs = "Avaliar 5 Estrelas ★",
    btnLater = "Mais tarde",
    btnExit = "Sair"
)

val ChineseSimpStrings = EnglishStrings.copy(
    tabClean = "清理",
    tabGenerator = "发生器",
    tabDiagnostics = "诊断",
    tabHistory = "历史",
    tabSettings = "设置",
    subClean = "扬声器排水除尘",
    subGenerator = "精准频率合成器",
    subDiagnostics = "音频健康与分贝仪",
    targetLoudspeaker = "主要扬声器",
    targetEarpiece = "听筒 (通话扬声器)",
    modeWaterEject = "声波排水",
    modeDustBlast = "声波除尘",
    modeDeepClean = "深度彻底清理",
    modeQuickBlast = "快速清理",
    btnStartCleaning = "开始清理",
    btnStopCleaning = "停止清理",
    statusCleaning = "正在强力清理中...",
    statusCompleted = "清理完成 ✓",
    tip1 = "1. 请将手机音量调至100%最大。",
    tip2 = "2. 将手机屏幕朝下，以45度角放置。",
    tip3 = "3. 断开耳机和蓝牙设备。",
    btnRateUs = "给5星好评 ★",
    btnLater = "稍后",
    btnExit = "退出"
)

val ChineseTradStrings = EnglishStrings.copy(
    tabClean = "清理",
    tabGenerator = "發生器",
    tabDiagnostics = "診斷",
    tabHistory = "歷史",
    tabSettings = "設定",
    subClean = "揚聲器排水除塵",
    subGenerator = "精準頻率合成器",
    subDiagnostics = "音訊健康與分貝儀",
    targetLoudspeaker = "主要揚聲器",
    targetEarpiece = "聽筒 (通話揚聲器)",
    modeWaterEject = "聲波排水",
    modeDustBlast = "聲波除塵",
    modeDeepClean = "深度徹底清理",
    modeQuickBlast = "快速清理",
    btnStartCleaning = "開始清理",
    btnStopCleaning = "停止清理",
    statusCleaning = "正在強力清理中...",
    statusCompleted = "清理完成 ✓",
    btnRateUs = "給予5星好評 ★",
    btnLater = "稍後",
    btnExit = "退出"
)

val RussianStrings = EnglishStrings.copy(
    tabClean = "Очистка",
    tabGenerator = "Генератор",
    tabDiagnostics = "Диагностика",
    tabHistory = "История",
    tabSettings = "Настройки",
    subClean = "Удаление воды и пыли",
    subGenerator = "Синтезатор частоты",
    subDiagnostics = "Звуковой тест и шумомер",
    targetLoudspeaker = "Основной динамик",
    targetEarpiece = "Слуховой динамик",
    modeWaterEject = "Удалить воду",
    modeDustBlast = "Очистить от пыли",
    modeDeepClean = "Глубокая очистка",
    modeQuickBlast = "Быстрая продувка",
    btnStartCleaning = "Начать очистку",
    btnStopCleaning = "Остановить",
    statusCleaning = "Очистка активна...",
    statusCompleted = "Очистка завершена ✓",
    tip1 = "1. Установите громкость на 100% МАКСИМУМ.",
    tip2 = "2. Положите телефон экраном вниз под углом 45°.",
    tip3 = "3. Отключите наушники.",
    btnRateUs = "Оценить на 5 звезд ★",
    btnLater = "Позже",
    btnExit = "Выход"
)

val KoreanStrings = EnglishStrings.copy(
    tabClean = "클리닝",
    tabGenerator = "주파수 생성기",
    tabDiagnostics = "진단",
    tabHistory = "기록",
    tabSettings = "설정",
    subClean = "스피커 물빼기 및 먼지 제거",
    subGenerator = "정밀 주파수 발생기",
    subDiagnostics = "음향 상태 & 데시벨 측정",
    targetLoudspeaker = "메인 스피커",
    targetEarpiece = "통화 리시버",
    modeWaterEject = "물 빼기",
    modeDustBlast = "먼지 털기",
    modeDeepClean = "정밀 딥 클리닝",
    modeQuickBlast = "빠른 분사",
    btnStartCleaning = "클리닝 시작",
    btnStopCleaning = "클리닝 정지",
    statusCleaning = "클리닝 진행 중...",
    statusCompleted = "클리닝 완료 ✓",
    btnRateUs = "별점 5점 주기 ★",
    btnLater = "나중에",
    btnExit = "종료"
)

val ItalianStrings = EnglishStrings.copy(
    tabClean = "Pulisci",
    tabGenerator = "Generatore",
    tabDiagnostics = "Diagnosi",
    tabHistory = "Cronologia",
    tabSettings = "Impostazioni",
    subClean = "Espulsore di acqua e polvere",
    subGenerator = "Sintetizzatore di frequenza",
    subDiagnostics = "Salute audio & Fonometro",
    targetLoudspeaker = "Altoparlante principale",
    targetEarpiece = "Ricevitore chiamata",
    modeWaterEject = "Espelli acqua",
    modeDustBlast = "Rimuovi polvere",
    modeDeepClean = "Pulizia profonda",
    modeQuickBlast = "Pulizia rapida",
    btnStartCleaning = "Avvia pulizia",
    btnStopCleaning = "Ferma pulizia",
    statusCleaning = "Pulizia in corso...",
    statusCompleted = "Pulizia completata ✓",
    btnRateUs = "Valuta 5 Stelle ★",
    btnLater = "Più tardi",
    btnExit = "Esci"
)

val IndonesianStrings = EnglishStrings.copy(
    tabClean = "Bersihkan",
    tabGenerator = "Generator",
    tabDiagnostics = "Diagnostik",
    tabHistory = "Riwayat",
    tabSettings = "Pengaturan",
    subClean = "Pengeluar Air & Debu",
    subGenerator = "Sintesis Frekuensi Suara",
    subDiagnostics = "Kesehatan Audio & dB Meter",
    targetLoudspeaker = "Speaker Utama",
    targetEarpiece = "Speaker Panggilan",
    modeWaterEject = "Keluarkan Air",
    modeDustBlast = "Bersihkan Debu",
    modeDeepClean = "Pembersihan Mendalam",
    modeQuickBlast = "Pembersihan Cepat",
    btnStartCleaning = "Mulai Bersihkan",
    btnStopCleaning = "Hentikan",
    statusCleaning = "Sedang Membersihkan...",
    statusCompleted = "Pembersihan Selesai ✓",
    tip1 = "1. Atur volume ponsel ke 100% MAKSIMAL.",
    tip2 = "2. Posisikan ponsel menghadap ke bawah 45°.",
    tip3 = "3. Cabut earphone.",
    btnRateUs = "Beri Nilai 5 Bintang ★",
    btnLater = "Nanti",
    btnExit = "Keluar"
)

val TurkishStrings = EnglishStrings.copy(
    tabClean = "Temizle",
    tabGenerator = "Jeneratör",
    tabDiagnostics = "Teşhis",
    tabHistory = "Geçmiş",
    tabSettings = "Ayarlar",
    subClean = "Su ve Toz Tahliye Edici",
    subGenerator = "Hassas Frekans Sentezleyici",
    subDiagnostics = "Hoparlör Sağlığı ve dB Metre",
    targetLoudspeaker = "Ana Hoparlör",
    targetEarpiece = "Ahize Hoparlörü",
    modeWaterEject = "Suyu Çıkar",
    modeDustBlast = "Tozu Temizle",
    modeDeepClean = "Derinlemesine Temizlik",
    modeQuickBlast = "Hızlı Temizlik",
    btnStartCleaning = "Temizliği Başlat",
    btnStopCleaning = "Temizliği Durdur",
    statusCleaning = "Temizlik yapılıyor...",
    statusCompleted = "Temizlik Tamamlandı ✓",
    btnRateUs = "5 Yıldız Ver ★",
    btnLater = "Daha sonra",
    btnExit = "Çıkış"
)

val VietnameseStrings = EnglishStrings.copy(
    tabClean = "Làm sạch",
    tabGenerator = "Bộ tạo tần số",
    tabDiagnostics = "Chẩn đoán",
    tabHistory = "Lịch sử",
    tabSettings = "Cài đặt",
    subClean = "Đẩy nước & Bụi bẩn",
    subGenerator = "Máy phát tần số chính xác",
    subDiagnostics = "Đo decibel & Sức khỏe loa",
    targetLoudspeaker = "Loa ngoài chính",
    targetEarpiece = "Loa thoại (Nghe gọi)",
    modeWaterEject = "Đẩy nước",
    modeDustBlast = "Thổi bụi",
    modeDeepClean = "Làm sạch sâu",
    modeQuickBlast = "Làm sạch nhanh",
    btnStartCleaning = "Bắt đầu làm sạch",
    btnStopCleaning = "Dừng làm sạch",
    statusCleaning = "Đang làm sạch...",
    statusCompleted = "Đã hoàn thành ✓",
    tip1 = "1. Bật âm lượng điện thoại lên 100% TỐI ĐA.",
    tip2 = "2. Đặt điện thoại úp mặt xuống một góc 45 độ.",
    tip3 = "3. Ngắt kết nối tai nghe.",
    btnRateUs = "Đánh giá 5 sao ★",
    btnLater = "Để sau",
    btnExit = "Thoát"
)

object AppStrings {
    fun get(code: String): StringResources {
        return when (code.lowercase()) {
            "es_es", "es" -> SpanishStrings
            "de_de", "de" -> GermanStrings
            "fr_fr", "fr" -> FrenchStrings
            "ja_jp", "ja" -> JapaneseStrings
            "ar_sa", "ar" -> ArabicStrings
            "hi_in", "hi" -> HindiStrings
            "pt_br", "pt" -> PortugueseStrings
            "zh_cn", "zh" -> ChineseSimpStrings
            "zh_tw" -> ChineseTradStrings
            "ru_ru", "ru" -> RussianStrings
            "ko_kr", "ko" -> KoreanStrings
            "it_it", "it" -> ItalianStrings
            "id_id", "id" -> IndonesianStrings
            "tr_tr", "tr" -> TurkishStrings
            "vi_vn", "vi" -> VietnameseStrings
            else -> EnglishStrings
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

@Composable
@ReadOnlyComposable
fun appStrings(): StringResources = LocalAppStrings.current
